
import React from 'react';
import { GoogleGenAI } from '@google/genai';
import { PersonalizedNewsFeedResult, PersonalizedNewsFeedItem } from '../types';
import { RssIcon } from './icons/RssIcon';

interface PersonalizedNewsFeedProps {
  ai: GoogleGenAI | null;
  onGetFeed: () => void;
  feedResult: PersonalizedNewsFeedResult | null;
  isLoading: boolean;
  error: string | null;
  personalizedNewsPdfAvailable: boolean; 
}

const PersonalizedNewsFeed: React.FC<PersonalizedNewsFeedProps> = ({
  ai,
  onGetFeed,
  feedResult,
  isLoading,
  error,
  personalizedNewsPdfAvailable,
}) => {
  return (
    <div className="bg-white shadow-xl rounded-lg p-6">
      <div className="flex items-center mb-4">
        <RssIcon className="w-7 h-7 text-accent mr-3" />
        <h3 className="text-xl font-semibold text-neutral">Personalized News (from Uploaded News PDF)</h3>
      </div>
      <p className="text-sm text-gray-600 mb-3">
        Get news and mentions relevant to your portfolio and watchlist stocks, extracted directly from your uploaded "Personalized News Document (PDF)".
      </p>
      <button
        onClick={onGetFeed}
        disabled={isLoading || !ai || !personalizedNewsPdfAvailable}
        className="bg-accent hover:bg-amber-600 text-white font-semibold py-2 px-4 rounded-lg shadow-md flex items-center transition duration-150 ease-in-out disabled:opacity-50"
        title={!ai ? "AI features disabled" : (!personalizedNewsPdfAvailable ? "Upload a 'Personalized News Document (PDF)' to enable this feature" : "Generate Personalized News Feed from News PDF")}
      >
        {isLoading ? (
          <>
            <div className="animate-spin rounded-full h-5 w-5 border-t-2 border-b-2 border-white mr-2"></div>
            Generating Feed...
          </>
        ) : (
          "Generate Feed from News PDF"
        )}
      </button>
      {!personalizedNewsPdfAvailable && !ai && (
         <p className="text-xs text-orange-600 mt-1">AI is disabled and no 'Personalized News Document (PDF)' is uploaded. This feature requires both.</p>
      )}
      {!personalizedNewsPdfAvailable && ai && (
         <p className="text-xs text-orange-600 mt-1">Please upload a 'Personalized News Document (PDF)' to generate the personalized news feed.</p>
      )}

      {error && (
        <div className="mt-4 p-3 bg-red-100 text-red-700 rounded-md">
          <p><strong className="font-semibold">Error:</strong> {error}</p>
        </div>
      )}

      {feedResult && !isLoading && !error && (
        <div className="mt-6">
          {feedResult.feedItems && feedResult.feedItems.length > 0 ? (
            <div className="space-y-4 max-h-96 overflow-y-auto">
              {feedResult.feedItems.map((item, index) => (
                <div key={index} className="p-3 bg-gray-50 rounded-md shadow-sm border border-gray-200">
                  <h4 className="font-semibold text-primary">{item.stockSymbol} {item.companyName && `(${item.companyName})`}</h4>
                  <p className="text-xs text-gray-500">Source: {item.source}</p>
                  <p className="text-sm text-gray-700 mt-1 whitespace-pre-wrap">{item.documentExtract}</p>
                  {item.tradingData && (
                    <div className="mt-2 pt-2 border-t border-gray-200 text-xs text-gray-600 grid grid-cols-2 gap-1">
                      {item.tradingData.closedOrLastPrice !== undefined && <p>Price: LKR {item.tradingData.closedOrLastPrice.toFixed(2)}</p>}
                      {item.tradingData.change !== undefined && <p className={item.tradingData.change >= 0 ? 'text-success' : 'text-error'}>Change: {item.tradingData.change.toFixed(2)}</p>}
                      {item.tradingData.changePercent !== undefined && <p className={item.tradingData.changePercent >= 0 ? 'text-success' : 'text-error'}>Change %: {item.tradingData.changePercent.toFixed(2)}%</p>}
                      {item.tradingData.volume !== undefined && <p>Volume: {item.tradingData.volume.toLocaleString()}</p>}
                    </div>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <p className="text-gray-500">No relevant news found in the 'Personalized News Document (PDF)' for your portfolio or watchlist stocks.</p>
          )}
        </div>
      )}
       <p className="mt-4 text-xs text-gray-500">
        This feed is generated by AI based solely on the content of the uploaded 'Personalized News Document (PDF)'.
      </p>
    </div>
  );
};

export default PersonalizedNewsFeed;
